DATASET:
  PART_COUNT: 1
  SIZE: 60000
  MAX_RESOLUTION_LEVEL: 5
MODEL:
  # LATENT_SPACE_SIZE: 256
  LATENT_SPACE_SIZE: 16
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  # MAPPING_LAYERS: 5
  MAPPING_LAYERS: 4
OUTPUT_DIR: mnist_results2
TRAIN:
  BASE_LEARNING_RATE: 0.0015
  EPOCHS_PER_LOD: 10
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 40
  LOD_2_BATCH_8GPU: [512, 256, 128,   64,   32,    32]
  LOD_2_BATCH_4GPU: [512, 256, 128,   64,   32,    16]
  LOD_2_BATCH_2GPU: [256, 256, 128,   64,   32,    16]
  LOD_2_BATCH_1GPU: [256, 256, 128,   64,   32,    16]
